### ISSUE TITLE
getting location info from catch sample

### ISSUE THREAD

**Issue by marksorel8** [MattCallahan-NOAA/rmisr#3]
Any idea what fields you would use from the catch sample data to join it with information on the location?

**Comment by MattCallahan-NOAA** [comment]
@gregwilke I am going to punt this to you.

**Comment by gregwilke** [comment]
Hi Mark,
The Catch sample data has a field called catch_location_code and location has location_code with a location_type=2 (for catch sample). That would be the primary connection in general. You can see API docs here: https://phish.rmis.org/docs/static/index.html, and you can find the RMIS data specification here (search for specification): https://www.rmpc.org/resources/documents/.

Also, you can direct questions about the RMIS project and RMIS data to me.  I work with the project, Matt is the R script guru who helped us by building this package.

Greg

**Comment by marksorel8** [comment]
So when I run the `get_catchsample()` function, the object that is returned does not include a catch_location_code field. Any idea why that may be?

**Comment by gregwilke** [comment]
Yes, issue confirmed. I was just looking at the schema for the initial response. There is some special treatment applied to this field and it is not being included in the output. I'll look at this tomorrow and let you know when we have a fix.

Appreciate you letting us know.


-----Original Message-----

**Comment by gregwilke** [comment]
I updated the catch sample data category and it is outputting the catch_location_code as intended with my testing now. Please let me know if that is not the case for you.

Greg

**Comment by marksorel8** [comment]
I can confirm that the catch_location_code is now a field in the data returned by the `get_catchsample()` function. Thank you!
