### ISSUE TITLE
Failing R CMD check

### ISSUE THREAD

**Issue by Ty-WDFW** [MattCallahan-NOAA/rmisr#5]
Looks like the `%>%` pipe is a big source of the errors which can be fixed with `usethis::use_pipe()`. The other big one is the referencing global functions, generally in package development you're going to want to use `::` for all the functions outside of the package and imported with `usethis::use_package()` on the package. 

Are you guys okay with me submitting pull requests here?

**Comment by MattCallahan-NOAA** [comment]
Go for it, thanks Ty.

**Comment by Ty-WDFW** [comment]
#6
